<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_-    (II )  - 7  2022 - 3048    27 09 22</name>
   <tag></tag>
   <elementGuidId>f963e3c8-c430-40b5-9ec6-8d2e1d7f479a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_rpNews_ctl00_HyperLink1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_rpNews_ctl00_HyperLink1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;सं ० सं ० - वि० प्रा ० (II ) नियुक्ति - ०7 / 2022 - 3048 / पटना दिनांक 27 /09 /22&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aef21b94-386b-4031-abbe-046c79f9cca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_rpNews_ctl00_HyperLink1</value>
      <webElementGuid>ff81c4a9-c29d-40cf-9d21-7bbef38417cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>UploadedImage/NewsDoc/30Mar202316442543.pdf</value>
      <webElementGuid>de06ed38-a912-4903-98d8-cb8c5bc71977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>8d15e731-aa7c-4af6-b84d-f4beec11718b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>सं ० सं ० - वि० प्रा ० (II ) नियुक्ति - ०7 / 2022 - 3048 / पटना दिनांक 27 /09 /22</value>
      <webElementGuid>6f35cbc8-2fef-400a-8620-b4b7a507e57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_rpNews_ctl00_HyperLink1&quot;)</value>
      <webElementGuid>5ff5968f-6626-42ba-87f0-ac36378890c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_rpNews_ctl00_HyperLink1']</value>
      <webElementGuid>8c1ec425-a21f-4dad-a866-3bd76b39cb76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ticker']/ul/li/div/div/a</value>
      <webElementGuid>8991cc22-17a1-4bb2-a5a2-73d8f7e82f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'सं ० सं ० - वि० प्रा ० (II ) नियुक्ति - ०7 / 2022 - 3048 / पटना दिनांक 27 /09 /22')]</value>
      <webElementGuid>7d393912-70ab-4eb4-b742-2b1d1a44a3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::a[1]</value>
      <webElementGuid>242d02fc-a948-40d0-969b-1de37d082d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='बिहार गजट - सं ० - वि० प्रा ० (II ) विविध - 01 / 2023 - 943 दिनांक 07/03 /23'])[1]/preceding::a[1]</value>
      <webElementGuid>f1e34648-a5dc-4099-b531-763f028876e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='सं ० सं ० - वि० प्रा ० (IV ) यो ० - 18 / 2021 (पार्ट II - 2266 / पटना दिनांक 27 /07 /22'])[1]/preceding::a[2]</value>
      <webElementGuid>ffdbff3b-4f4f-4b45-8812-47db865f74dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='सं ० सं ० - वि० प्रा ० (II ) नियुक्ति - ०7 / 2022 - 3048 / पटना दिनांक 27 /09 /22']/parent::*</value>
      <webElementGuid>c7120522-89d8-4e40-9f0d-2887b533d7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'UploadedImage/NewsDoc/30Mar202316442543.pdf')]</value>
      <webElementGuid>0fe401bb-9124-4dd8-b792-769763ce3e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/a</value>
      <webElementGuid>f65e61d9-4e0f-408d-8bb3-236938384fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_rpNews_ctl00_HyperLink1' and @href = 'UploadedImage/NewsDoc/30Mar202316442543.pdf' and (text() = 'सं ० सं ० - वि० प्रा ० (II ) नियुक्ति - ०7 / 2022 - 3048 / पटना दिनांक 27 /09 /22' or . = 'सं ० सं ० - वि० प्रा ० (II ) नियुक्ति - ०7 / 2022 - 3048 / पटना दिनांक 27 /09 /22')]</value>
      <webElementGuid>769a75e7-fd91-4039-a817-23c030c970d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
