<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_-    (IV )   - 18  2021 ( II - 2266    27 07 22</name>
   <tag></tag>
   <elementGuidId>c3da955f-826d-424b-a14f-05451ca77b1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_rpNews_ctl02_HyperLink1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_rpNews_ctl02_HyperLink1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;सं ० सं ० - वि० प्रा ० (IV ) यो ० - 18 / 2021 (पार्ट II - 2266 / पटना दिनांक 27 /07 /22&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>56f0b48a-6721-448c-9f34-8f4fe40cad51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_rpNews_ctl02_HyperLink1</value>
      <webElementGuid>6002a352-ffe9-437e-996a-28d437f977bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>UploadedImage/NewsDoc/30Mar202314313723.pdf</value>
      <webElementGuid>61e84cd6-2e02-4c6a-a6aa-6db9fb34a83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6b9d5022-4b1e-49c0-9e2d-8f1b9b2120a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>सं ० सं ० - वि० प्रा ० (IV ) यो ० - 18 / 2021 (पार्ट II - 2266 / पटना दिनांक 27 /07 /22</value>
      <webElementGuid>4199d352-c873-4116-96b2-54fc84c4b06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_rpNews_ctl02_HyperLink1&quot;)</value>
      <webElementGuid>20f51710-99fe-4c39-bed3-4f3fb8cbe1eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_rpNews_ctl02_HyperLink1']</value>
      <webElementGuid>ceef6f04-e11b-4d59-b1a4-18389f764396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ticker']/ul/li[3]/div/div/a</value>
      <webElementGuid>f0186a17-b842-4965-8b37-287056eaf891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'सं ० सं ० - वि० प्रा ० (IV ) यो ० - 18 / 2021 (पार्ट II - 2266 / पटना दिनांक 27 /07 /22')]</value>
      <webElementGuid>4b49777f-1a1a-42ff-9b9c-d29da1d31339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='बिहार गजट - सं ० - वि० प्रा ० (II ) विविध - 01 / 2023 - 943 दिनांक 07/03 /23'])[1]/following::a[1]</value>
      <webElementGuid>f18ce707-2cb8-44f0-a185-974715ce6c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='सं ० सं ० - वि० प्रा ० (II ) नियुक्ति - ०7 / 2022 - 3048 / पटना दिनांक 27 /09 /22'])[1]/following::a[2]</value>
      <webElementGuid>2cf14ab7-4d48-4247-bfbd-3fc791092031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='सं ० सं ० - वि० प्रा ० (II ) नियुक्ति - ०9 / 2022 - 3049 / पटना दिनांक 27 /09 /22'])[1]/preceding::a[1]</value>
      <webElementGuid>e5db8377-cfc8-41a0-a400-876445ff0433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='सं ० सं ० - वि० प्रा ० (IV ) यो ० - 18 / 2021 (पार्ट II - 2266 / पटना दिनांक 27 /07 /22']/parent::*</value>
      <webElementGuid>ccd4de4c-d1e7-465a-9cbd-754e3cd2b4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'UploadedImage/NewsDoc/30Mar202314313723.pdf')]</value>
      <webElementGuid>8caaff3a-1e8a-40a7-9b96-8ec3f90f01e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/a</value>
      <webElementGuid>47dbea0c-f00e-4f95-9426-383157dbbc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_rpNews_ctl02_HyperLink1' and @href = 'UploadedImage/NewsDoc/30Mar202314313723.pdf' and (text() = 'सं ० सं ० - वि० प्रा ० (IV ) यो ० - 18 / 2021 (पार्ट II - 2266 / पटना दिनांक 27 /07 /22' or . = 'सं ० सं ० - वि० प्रा ० (IV ) यो ० - 18 / 2021 (पार्ट II - 2266 / पटना दिनांक 27 /07 /22')]</value>
      <webElementGuid>18d308db-7ddf-46d3-9580-31d2e7023f5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
