<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1st Semester Special Examination Program 2024</name>
   <tag></tag>
   <elementGuidId>a02df35c-3171-4675-be70-1e8cc2d40d66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl06_HyperLink1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl06_HyperLink1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;1st Semester Special Examination Program 2024&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0b5aa0df-0274-42aa-a6e0-4eedab2786e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl06_HyperLink1</value>
      <webElementGuid>2d511c47-613b-4cfe-b595-c10cd319b985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>NoticePdf/08Apr202415330460.pdf</value>
      <webElementGuid>ddbdac00-1c7a-4367-a52c-e9830bf4ecf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a606af31-b114-464d-a7d9-300161dad287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1st Semester Special Examination Program 2024</value>
      <webElementGuid>42eacf3d-a739-4c4a-97f2-263f0abbc4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl06_HyperLink1&quot;)</value>
      <webElementGuid>cb3a50bf-c304-4475-b7c0-309b6b3acada</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl06_HyperLink1']</value>
      <webElementGuid>b7b254ad-3d37-4f73-81a4-bb12c8a1f96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div2']/ul/div[7]/a</value>
      <webElementGuid>d2ec6198-2402-48a3-be4d-d7e0d5f9ca98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'1st Semester Special Examination Program 2024')]</value>
      <webElementGuid>04b138c3-a135-4a58-afc4-65daed4509cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Info'])[1]/preceding::a[1]</value>
      <webElementGuid>b51101e2-28ed-4673-9953-cee1eebd31be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bihar Engineering University, Patna'])[2]/preceding::a[2]</value>
      <webElementGuid>b0bf7cba-0999-452c-8acc-50457a9c8967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1st Semester Special Examination Program 2024']/parent::*</value>
      <webElementGuid>c6c12f1e-29cc-47c2-96d6-bfb7f6896acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'NoticePdf/08Apr202415330460.pdf')]</value>
      <webElementGuid>07a5eac2-7709-4fb7-8600-b6fbe3e7860d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a</value>
      <webElementGuid>3460f50c-feec-4ac4-921a-f4ed28dcf204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl06_HyperLink1' and @href = 'NoticePdf/08Apr202415330460.pdf' and (text() = '1st Semester Special Examination Program 2024' or . = '1st Semester Special Examination Program 2024')]</value>
      <webElementGuid>345830c2-dbe5-4b5f-ac7f-370e8eeb4486</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
