<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_5th Semester Examination Program 2023</name>
   <tag></tag>
   <elementGuidId>ad78d8e6-6653-463e-b77c-e409e9c5f090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl01_HyperLink1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl01_HyperLink1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;5th Semester Examination Program 2023&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>864f1fda-8a85-4531-b150-6b87cd9173c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl01_HyperLink1</value>
      <webElementGuid>55a3149c-7ca8-47e3-a2fd-97acb55cccea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>NoticePdf/21May202418590175.pdf</value>
      <webElementGuid>795d0512-66f1-41ac-a7f5-df2e766174b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>2db7c451-11b0-488d-b79e-e2a1b3c860b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5th Semester Examination Program 2023</value>
      <webElementGuid>6bb2fcdf-ce89-4d83-8d56-f5d7a7f1f61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl01_HyperLink1&quot;)</value>
      <webElementGuid>7725802d-769b-428b-b43c-f83bbd71f4a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl01_HyperLink1']</value>
      <webElementGuid>afafd2ad-bb31-41c0-a061-e98d0128f068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div2']/ul/div[2]/a</value>
      <webElementGuid>6a5c0df5-ffe5-45b9-abf8-5ca5e8c9429e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'5th Semester Examination Program 2023')]</value>
      <webElementGuid>eb49cef1-a358-4e99-998d-99ab3d3c62e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5th Semester Examination Program 2023']/parent::*</value>
      <webElementGuid>8965a920-4e23-40cb-af03-772c5366dc67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'NoticePdf/21May202418590175.pdf')]</value>
      <webElementGuid>d9f18c37-e980-423a-9c6b-c59a5877535a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>a4d10e2c-a6fe-443e-97eb-08a0f183b26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl01_HyperLink1' and @href = 'NoticePdf/21May202418590175.pdf' and (text() = '5th Semester Examination Program 2023' or . = '5th Semester Examination Program 2023')]</value>
      <webElementGuid>af020543-fe5b-4420-b380-a6ca73420790</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
