<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_5th Semester Examination Form</name>
   <tag></tag>
   <elementGuidId>b416d8a3-ee12-41d4-9779-d13dfd2400df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl04_HyperLink1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl04_HyperLink1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;5th Semester Examination Form&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>807ea3ac-de98-43f4-b9fd-315199431eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl04_HyperLink1</value>
      <webElementGuid>60ba7ed7-89df-4355-b7d7-772929be8020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>NoticePdf/27Apr202417521467.pdf</value>
      <webElementGuid>a18867e5-d668-4e7c-85c0-78f80c135220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>65a3535d-7445-448a-a9d5-450f16177956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5th Semester Examination Form</value>
      <webElementGuid>a993df64-16be-4ef4-89cf-23c6b1ca2628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl04_HyperLink1&quot;)</value>
      <webElementGuid>9097890f-fc97-418c-bf6a-c12f0810ebd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl04_HyperLink1']</value>
      <webElementGuid>7ab42359-a33f-4a4a-ba9d-796d5fe3b2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div2']/ul/div[5]/a</value>
      <webElementGuid>7794d17c-d3a7-41a5-9c7f-9e5e3930f8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'5th Semester Examination Form')]</value>
      <webElementGuid>4a6aa09e-e71e-4e0f-8a6a-0689254c33cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revised Academic schedule for 8th Semester'])[1]/following::a[1]</value>
      <webElementGuid>eabe5763-cfc8-472a-8b28-dc85e04e3116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5th Semester Examination Form']/parent::*</value>
      <webElementGuid>59606284-346e-4308-b6d2-4746ea3c52a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'NoticePdf/27Apr202417521467.pdf')]</value>
      <webElementGuid>5add7500-e37a-489c-a5de-55457ba1e9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>5850fe93-6ae4-44af-a563-3df1cde7e29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_rpUsefulInfoEn_ctl04_HyperLink1' and @href = 'NoticePdf/27Apr202417521467.pdf' and (text() = '5th Semester Examination Form' or . = '5th Semester Examination Form')]</value>
      <webElementGuid>9a69c93f-a043-4107-bfe9-75b91ac70e67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
