<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download</name>
   <tag></tag>
   <elementGuidId>9e3d2e43-c67a-42c3-a539-209ea12a6b05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_grdcollegeeng_ctl03_lnl_url</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_grdcollegeeng_ctl03_lnl_url']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl00_ContentPlaceHolder1_grdcollegeeng_ctl03_lnl_url</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81ae6ee3-7fd9-40e2-9b25-eabab5ab09e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/BEUP/UploadedImage/Act_Image/doct202391923335973.pdf</value>
      <webElementGuid>884cf5f8-0161-430e-8bb8-2bf98f497d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_grdcollegeeng_ctl03_lnl_url</value>
      <webElementGuid>d57b83fd-72a6-459d-81b0-7cbdc323d501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6a596c63-95a7-4c4e-85fd-88d4a5dde4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-success btn</value>
      <webElementGuid>aae1fbeb-c30c-4fb1-9126-a5d73b76093d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                             Download</value>
      <webElementGuid>54c70cde-5136-4ae5-94e2-096531d97708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_grdcollegeeng_ctl03_lnl_url&quot;)</value>
      <webElementGuid>3dfffb1d-2a66-4321-a377-9a98aadbe6e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_grdcollegeeng_ctl03_lnl_url']</value>
      <webElementGuid>430a71bd-c38b-41de-9594-9a095cafaa79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_grdcollegeeng']/tbody/tr[3]/td[3]/a</value>
      <webElementGuid>c3285d9a-0587-47b4-8f40-b5bf6030ba4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Download')])[2]</value>
      <webElementGuid>4c43e825-a9a8-42e7-adab-a9c0aa93fd5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STATUTES OF THE UNIVERSITY [Vide Section 28 and 29 (1) of the Act]'])[1]/following::a[1]</value>
      <webElementGuid>a6d82620-bf37-4ded-b807-96a83ff8e7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bihar Engineering University, Patna'])[2]/preceding::a[1]</value>
      <webElementGuid>cd8072a1-437d-4e83-80f4-fd196397b56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::a[1]</value>
      <webElementGuid>cefec211-7c55-433d-8c34-5af597de471e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/BEUP/UploadedImage/Act_Image/doct202391923335973.pdf')]</value>
      <webElementGuid>0782f48a-9a2e-4f9f-91c1-e2059ca5504a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/a</value>
      <webElementGuid>38deff7f-410c-4b8a-8286-5a6fe1779af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/BEUP/UploadedImage/Act_Image/doct202391923335973.pdf' and @id = 'ctl00_ContentPlaceHolder1_grdcollegeeng_ctl03_lnl_url' and (text() = '
                                             Download' or . = '
                                             Download')]</value>
      <webElementGuid>f6ce4d23-8f7e-4816-8b1b-ec9d90d14da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lnl_url']</value>
      <webElementGuid>597d0b96-803a-4548-a857-06e763bec854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_grdcollegeeng']/tbody/tr[2]/td[3]/a</value>
      <webElementGuid>f55299c9-820a-4ca5-875b-60dcaead208d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download')]</value>
      <webElementGuid>f04ae9f6-2452-4102-aae9-aff980afa8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document'])[1]/following::a[1]</value>
      <webElementGuid>782aab97-3fdf-4df4-a4a0-713f4a8adf9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/BEUP/UploadedImage/Act_Image/doct202333014740990.pdf')]</value>
      <webElementGuid>66b3054e-eaf8-43f2-b239-91f1fbdf25cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>1efdb812-8b57-4e67-8196-3958162e5317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/BEUP/UploadedImage/Act_Image/doct202333014740990.pdf' and @id = 'ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lnl_url' and (text() = '
                                             Download' or . = '
                                             Download')]</value>
      <webElementGuid>42cc7301-8c55-4acd-966b-eeccac7b9eab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
