<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpswww.scesupaul.org</name>
   <tag></tag>
   <elementGuidId>00cb1202-fd35-4d81-bc15-0d4817490f0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_grdcollegeeng_ctl09_HyperLink1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_grdcollegeeng_ctl09_HyperLink1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;https://www.scesupaul.org/&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>995e25ab-edd8-4ff7-9ea5-ddbda84e8708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_grdcollegeeng_ctl09_HyperLink1</value>
      <webElementGuid>5261a450-b198-46cd-9740-05d365c004b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.scesupaul.org/</value>
      <webElementGuid>bef9fb21-b4bc-4573-bfb8-cd1bcfcc93cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>8da99e1c-9f24-4e22-9a17-ea7c7852b220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://www.scesupaul.org/</value>
      <webElementGuid>ec870f04-1734-4fd0-aa4c-6bd14d3a68d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_grdcollegeeng_ctl09_HyperLink1&quot;)</value>
      <webElementGuid>af456172-7028-4f5f-b033-7dca9299e04b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_grdcollegeeng_ctl09_HyperLink1']</value>
      <webElementGuid>c58b7e58-5bc2-4f82-9318-c58aa6efc5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_grdcollegeeng']/tbody/tr[9]/td[3]/a</value>
      <webElementGuid>42f40108-7c5b-490c-9c58-8b639d9e33eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://www.scesupaul.org/')]</value>
      <webElementGuid>d765dfeb-cc2a-4b60-adad-3cf2032fe2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUPAUL COLLEGE OF ENGINEERING, SUPAUL'])[1]/following::a[1]</value>
      <webElementGuid>6afb39f9-7e90-469e-9baf-18cb38f2f3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAKHTIYARPUR COLLEGE OF ENGINEERING, PATNA'])[1]/preceding::a[2]</value>
      <webElementGuid>e770d7b5-74be-4a45-86b1-c5ce4075a5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://www.scesupaul.org/']/parent::*</value>
      <webElementGuid>c643a4a4-cd4e-4abc-a4df-d1dfd3be528d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.scesupaul.org/')]</value>
      <webElementGuid>da13e3dc-d955-4cd6-ab55-c36ea46c6b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[3]/a</value>
      <webElementGuid>d1b621b7-32ed-4f71-a165-cc71fe57529a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_grdcollegeeng_ctl09_HyperLink1' and @href = 'https://www.scesupaul.org/' and (text() = 'https://www.scesupaul.org/' or . = 'https://www.scesupaul.org/')]</value>
      <webElementGuid>c33040dc-7330-44e1-b677-074b9ee13951</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
