<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpswww.mcemotihari.ac.in</name>
   <tag></tag>
   <elementGuidId>3b0cb8f9-b653-401b-9147-8d3967717343</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_grdcollegeeng_ctl05_HyperLink1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_grdcollegeeng_ctl05_HyperLink1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;https://www.mcemotihari.ac.in/&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d26a626a-b9b0-43be-ba5f-c58a7293ef1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_grdcollegeeng_ctl05_HyperLink1</value>
      <webElementGuid>cd98cf90-b277-4925-b3d6-3ca008cd885a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mcemotihari.ac.in/</value>
      <webElementGuid>f744bb4e-f63a-451e-a1e8-dec6ae3acbcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>69855b49-6133-47d9-bcdc-ea89e4e37bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://www.mcemotihari.ac.in/</value>
      <webElementGuid>a5437b0a-e065-4ab4-9ea5-3d7bf19f2226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_grdcollegeeng_ctl05_HyperLink1&quot;)</value>
      <webElementGuid>9e5f913a-fa42-4caa-9e19-c030e6919056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_grdcollegeeng_ctl05_HyperLink1']</value>
      <webElementGuid>3dea1c38-f4c6-4ce2-86fb-f74a29cc59fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_grdcollegeeng']/tbody/tr[5]/td[3]/a</value>
      <webElementGuid>e1aa9b86-8da0-405e-94b7-b4cdccab794d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://www.mcemotihari.ac.in/')]</value>
      <webElementGuid>0657adfc-8a53-44e0-b0d5-47b7df34b778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MOTIHARI COLLEGE OF ENGINEERING, MOTIHARI'])[1]/following::a[1]</value>
      <webElementGuid>241e6c85-625b-44c6-9600-bc58e95a9e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOK NAYAK JAI PRAKASH INSTITUTE OF TECHNOLOGY, CHAPRA'])[1]/preceding::a[2]</value>
      <webElementGuid>356caeea-49b7-4179-ba28-4dfd247be089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://www.mcemotihari.ac.in/']/parent::*</value>
      <webElementGuid>c5ebbb07-c731-4f82-946a-d8965c0016e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.mcemotihari.ac.in/')]</value>
      <webElementGuid>f09a617c-3734-4841-b96f-d9a802101eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/a</value>
      <webElementGuid>57590485-6288-4f3b-a6b9-5c1b13616c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_grdcollegeeng_ctl05_HyperLink1' and @href = 'https://www.mcemotihari.ac.in/' and (text() = 'https://www.mcemotihari.ac.in/' or . = 'https://www.mcemotihari.ac.in/')]</value>
      <webElementGuid>1b7dfa41-370c-4315-af88-dade884d1f85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
