<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_milliakcet.org</name>
   <tag></tag>
   <elementGuidId>5480fe88-3e61-4d78-a594-9cc6af4bcf62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_grdcollegeeng_ctl13_HyperLink1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_grdcollegeeng_ctl13_HyperLink1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;milliakcet.org&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8cd99b83-c073-4321-b28b-e16263a52f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_grdcollegeeng_ctl13_HyperLink1</value>
      <webElementGuid>9850e2d3-d35e-4d05-afc8-321ffedadfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>milliakcet.org</value>
      <webElementGuid>949189f1-7294-46d3-aab9-b76fd597a0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>1f92c41e-886c-4d88-bfd5-88d2d8cc18c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>milliakcet.org</value>
      <webElementGuid>5d5c6718-af88-46b0-8fad-0753b46c9b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_grdcollegeeng_ctl13_HyperLink1&quot;)</value>
      <webElementGuid>9703e6af-7c4b-4fda-b106-e4ab5910b64d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_grdcollegeeng_ctl13_HyperLink1']</value>
      <webElementGuid>3180cc6a-875e-45a1-83ce-80f073d4d08b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_grdcollegeeng']/tbody/tr[13]/td[3]/a</value>
      <webElementGuid>5b4a7120-ad9f-4206-bd4e-c852334d5471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'milliakcet.org')]</value>
      <webElementGuid>9a2d4563-06ae-43ec-a69d-5e066e2ef854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Millia Kishanganj College of Engineering &amp; Technology, Kishanganj'])[1]/following::a[1]</value>
      <webElementGuid>e11068a0-9697-468d-9694-040dfe09b007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Millia Institute of Technology, Purnia'])[1]/preceding::a[2]</value>
      <webElementGuid>632e4e2c-dd9d-4b78-8321-8d69af1956e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='milliakcet.org']/parent::*</value>
      <webElementGuid>723bb35f-7993-4a1d-812d-63836cc8cd95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'milliakcet.org')]</value>
      <webElementGuid>62ffcef4-eb0f-4e70-8e4c-323739a30279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[3]/a</value>
      <webElementGuid>3271588e-2816-49ea-a031-75f51b7bf334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_grdcollegeeng_ctl13_HyperLink1' and @href = 'milliakcet.org' and (text() = 'milliakcet.org' or . = 'milliakcet.org')]</value>
      <webElementGuid>b13c5559-7acc-4e96-a5de-fccf64742b84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
