<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_VIDYA VIHAR INSTITUTE OF TECHNOLOGY,PURNIA</name>
   <tag></tag>
   <elementGuidId>47106dd5-d067-4544-b6d8-0d737d32cb2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lblName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lblName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;VIDYA VIHAR INSTITUTE OF TECHNOLOGY,PURNIA&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>94113427-2ab2-427f-b73b-658b2a1eeb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lblName</value>
      <webElementGuid>3e252043-b34e-48b4-b145-e4a7261a0bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VIDYA VIHAR INSTITUTE OF TECHNOLOGY,PURNIA</value>
      <webElementGuid>4601b122-3921-41f7-9452-aa6b53b13ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lblName&quot;)</value>
      <webElementGuid>7594174d-e55a-46e7-97be-0077f22fe6ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lblName']</value>
      <webElementGuid>20769a43-5cc0-483b-8ce6-ab0e5af2f679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_grdcollegeeng']/tbody/tr[2]/td[2]/span</value>
      <webElementGuid>be90db04-86e0-44c5-b0cd-5d20b2efef2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document'])[1]/following::span[1]</value>
      <webElementGuid>9e4559f0-9ac1-4eec-b927-c7f6aed62976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Website'])[1]/following::span[1]</value>
      <webElementGuid>65e950b5-8a02-4a9a-a66d-57c8a5c5aa48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NETAJI SUBHAS INSTITUTE OF TECHNOLOGY,BIHTA'])[1]/preceding::span[1]</value>
      <webElementGuid>146b44df-e0e4-47ff-b065-88be64fc6e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VIDYA VIHAR INSTITUTE OF TECHNOLOGY,PURNIA']/parent::*</value>
      <webElementGuid>6ca86914-4616-4537-a033-4fecb5c86139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>c64f2190-5e06-43bb-85a4-44c18e184182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lblName' and (text() = 'VIDYA VIHAR INSTITUTE OF TECHNOLOGY,PURNIA' or . = 'VIDYA VIHAR INSTITUTE OF TECHNOLOGY,PURNIA')]</value>
      <webElementGuid>8fbed62e-377e-460d-8dc8-e432b5f0f7f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
