<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Verify you are human by completing t_f3553f</name>
   <tag></tag>
   <elementGuidId>f5b95c13-267a-4f73-a186-db822fe76762</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cf-chl-widget-i1l9w</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='cf-chl-widget-i1l9w']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Widget containing a Cloudflare security challenge&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d5200498-483d-454a-9b91-3e3a4d1dc962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/g/turnstile/if/ov2/av0/rcv0/0/i1l9w/0x4AAAAAAADnPIDROrmt1Wwj/dark/normal</value>
      <webElementGuid>457e684a-4bce-4294-9e09-892cc959dbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>cross-origin-isolated; fullscreen; autoplay</value>
      <webElementGuid>b15145c8-68da-4e25-86e3-847d04ac38f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-same-origin allow-scripts allow-popups</value>
      <webElementGuid>6e5ac724-cb5b-4d7e-8d59-a061106107ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cf-chl-widget-i1l9w</value>
      <webElementGuid>38b0933c-99c2-415e-9893-de7d8eff2407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ca49e168-69a4-4614-a3cc-5c7d468f70ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Widget containing a Cloudflare security challenge</value>
      <webElementGuid>965459c8-b915-4b7f-aef8-ac2f8a6817fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cf-chl-widget-i1l9w&quot;)</value>
      <webElementGuid>672b01b2-1617-488a-9334-9d74818c44ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='cf-chl-widget-i1l9w']</value>
      <webElementGuid>431e61ef-f2c6-4027-a14e-c383c914065b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='turnstile-wrapper']/div/iframe</value>
      <webElementGuid>57e10a2b-ba32-41a9-98f6-8f0031abc497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>47b96aeb-bb04-41a7-8efd-0a09a67a30e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/g/turnstile/if/ov2/av0/rcv0/0/i1l9w/0x4AAAAAAADnPIDROrmt1Wwj/dark/normal' and @id = 'cf-chl-widget-i1l9w' and @title = 'Widget containing a Cloudflare security challenge']</value>
      <webElementGuid>850c1e72-103e-4b70-a3ca-3dca53e72253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
