<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkbox (2)</name>
   <tag></tag>
   <elementGuidId>a96fc3b2-d49c-4f97-9ee0-299118b2f55c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Verify you are human&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45ec6625-770a-409e-b882-42d108c3c964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c27269df-c861-468b-b718-c113334cccb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;challenge-stage&quot;)/div[@class=&quot;cb-c&quot;]/label[@class=&quot;cb-lb&quot;]/input[1]</value>
      <webElementGuid>78ace435-a213-4047-8397-fbc7ff9e49af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Just a moment/iframe_Verify you are human by completing t_f3553f</value>
      <webElementGuid>da5e0466-ea73-45c8-beac-257fd51913ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>cb060933-d4e8-4f4b-874c-4ed520629cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='challenge-stage']/div/label/input</value>
      <webElementGuid>795a4ffa-cbd2-436f-86a9-86f496d6e1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b7d66757-0bd6-4692-93bf-573df7d77b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>00e45d4a-c3c0-439a-86a9-83da1246a977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
